# Nombre de la aplicacion
spring.application.name=api_rest

# 1. Apuntamos a la IP del contenedor Podman en lugar de localhost
spring.datasource.url=jdbc:sqlserver://10.10.1.1:1433;databaseName=MimosDemo;encrypt=false

# Hibernate: validate asegura que las tablas existan pero NO las altera ni borra
spring.datasource.username=api_mimos_user
spring.datasource.password=MimosDev2026*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate: validate asegura que las tablas existan pero NO las altera ni borra
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Evita que Spring cambie tus nombres a min\u00fasculas
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Le indica a Hibernate que busque exactamente en el esquema dbo
spring.jpa.properties.hibernate.default_schema=dbo

# Puerto de la API
server.port=8081